name: Capstone CI

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set Mock Environment Variables
        run: |
          echo "SENDGRID_API_KEY=mock_sendgrid_api_key" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY=mock_stripe_secret_key" >> $GITHUB_ENV
          echo "STRIPE_PUBLISHABLE_KEY=mock_stripe_publishable_key" >> $GITHUB_ENV

      - name: Type check server
        run: npm run type-check -w=server

      - name: Type check client
        run: npm run type-check -w=client

      - name: Lint server
        run: npm run lint -w=server

      - name: Lint client
        run: npm run lint -w=client

      - name: Test server with mocked environment
        run: npm run test -w=server

      - name: Test client (unit)
        run: npm run test:unit -w=client

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start server for E2E tests and wait for readiness
        run: |
          npm run dev -w=server &
          while ! curl --output /dev/null --silent --head --fail http://localhost:3000/health; do
            echo "Waiting for server to be ready..."
            sleep 1
          done
        env:
          DB_USER: username
          DB_PASSWORD: password
          DB_NAME: testdb
          DB_HOST: localhost
          PORT: 3000

      - name: Build front end for E2E tests
        run: npm run build -w=client
        env:
          VITE_API_ORIGIN: http://localhost:3000
          VITE_API_PATH: /v1/trpc

      - name: Wait for server to startup
        uses: Jtalk/url-health-check-action@v3.2
        with:
          max-attempts: 5
          retry-delay: 5s
          url: http://localhost:3000/health

      - name: Test client E2E
        run: npm run test:e2e -w=client

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 7
