name: Capstone CI

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm ci
    - name: Type check client
      run: npm run type-check -w client
    - name: Type check server
      run: npm run typecheck -w server
    - name: Lint client code
      run: npm run lint -w client
    - name: Lint server code
      run: npm run lint -w server
    - name: Run client unit tests
      run: npm run test:unit -w client
    - name: Run server tests
      env:
        DB_TYPE: 'pg-mem'
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      run: npm run test:mem -w server

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start server for E2E tests
      run: npm run dev -w=server &
      env:
        DB_TYPE: 'pg-mem'
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        PORT: 3000
    - name: Build front end for E2E tests
      run: npm run build -w=client
      env:
        VITE_API_ORIGIN: http://localhost:3000
        VITE_API_PATH: /v1/trpc
    - name: Wait for server to startup
      uses: Jtalk/url-health-check-action@v3.2
      with:
        max-attempts: 5
        retry-delay: 5s
        url: http://localhost:3000/health
    - name: Run client E2E tests with debug logs
      run: DEBUG=pw:api npm run test:e2e -w=client
      env:
        PWDEBUG: console
    - name: Upload Playwright trace files
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-traces
        path: client/test-results/**/trace.zip
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: client/playwright-report/
        retention-days: 7
  